# Makefile for {{.ProjectName}}

run:
	go run cmd/main.go

build:
	go build -o bin/{{.ProjectName}} cmd/main.go

migrate-up:
	go run db/migrate.go $(DB) up

migrate-down:
	go run db/migrate.go $(DB) down

migrate-reset:
	go run db/migrate.go $(DB) reset
